server:
  port: ${PORT}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: izum-bank-app
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true
    default-schema: public
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: true
    show_sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    to: ${SPRING_MAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true